# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/learning_ML',
                'doc_host': 'https://gpetrousov.github.io',
                'git_url': 'https://github.com/gpetrousov/learning_ML',
                'lib_path': 'mikroml'},
  'syms': { 'mikroml.matmul': {'mikroml.matmul.chuncks': ('matmul.html#chuncks', 'mikroml/matmul.py')},
            'mikroml.minibatch': {'mikroml.minibatch.accuracy': ('minibatch.html#accuracy', 'mikroml/minibatch.py')}}}
