# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/04_minibatch.ipynb.

# %% auto 0
__all__ = ['accuracy']

# %% ../notebooks/04_minibatch.ipynb 34
def accuracy(preds, targs):
    """ The average of the correctly predicted numbers """
    return (preds.argmax(dim=1)==targs).float().mean()
